version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=carlos
      - POSTGRES_PASSWORD=admin1234
    ports:
      - 5433:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
